//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_WS_Gen13.Calculadora_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Calculadora_Service.Calculadora_ServiceSoap")]
    public interface Calculadora_ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponse HelloWorld(Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponse> HelloWorldAsync(Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        double Suma(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Suma", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumaAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        double Resta(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Resta", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RestaAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        double Multiplicacion(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiplicacion", ReplyAction="*")]
        System.Threading.Tasks.Task<double> MultiplicacionAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        double Division(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Division", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DivisionAsync(double a, double b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Calculadora_ServiceSoapChannel : Cliente_WS_Gen13.Calculadora_Service.Calculadora_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Calculadora_ServiceSoapClient : System.ServiceModel.ClientBase<Cliente_WS_Gen13.Calculadora_Service.Calculadora_ServiceSoap>, Cliente_WS_Gen13.Calculadora_Service.Calculadora_ServiceSoap {
        
        public Calculadora_ServiceSoapClient() {
        }
        
        public Calculadora_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Calculadora_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calculadora_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Calculadora_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponse Cliente_WS_Gen13.Calculadora_Service.Calculadora_ServiceSoap.HelloWorld(Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest inValue = new Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest();
            inValue.Body = new Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequestBody();
            Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponse retVal = ((Cliente_WS_Gen13.Calculadora_Service.Calculadora_ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponse> Cliente_WS_Gen13.Calculadora_Service.Calculadora_ServiceSoap.HelloWorldAsync(Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente_WS_Gen13.Calculadora_Service.HelloWorldResponse> HelloWorldAsync() {
            Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest inValue = new Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequest();
            inValue.Body = new Cliente_WS_Gen13.Calculadora_Service.HelloWorldRequestBody();
            return ((Cliente_WS_Gen13.Calculadora_Service.Calculadora_ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double Suma(double a, double b) {
            return base.Channel.Suma(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SumaAsync(double a, double b) {
            return base.Channel.SumaAsync(a, b);
        }
        
        public double Resta(double a, double b) {
            return base.Channel.Resta(a, b);
        }
        
        public System.Threading.Tasks.Task<double> RestaAsync(double a, double b) {
            return base.Channel.RestaAsync(a, b);
        }
        
        public double Multiplicacion(double a, double b) {
            return base.Channel.Multiplicacion(a, b);
        }
        
        public System.Threading.Tasks.Task<double> MultiplicacionAsync(double a, double b) {
            return base.Channel.MultiplicacionAsync(a, b);
        }
        
        public double Division(double a, double b) {
            return base.Channel.Division(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DivisionAsync(double a, double b) {
            return base.Channel.DivisionAsync(a, b);
        }
    }
}
